### ISSUE TITLE
Wrong cmake condition in the main CMakeLists.txt

### ISSUE THREAD

**Issue by wkjung** [intel/hexl#102]
I guess the cmake condition testing whether to use `GNUInstallDirs` below should be `UNIX`, not `LINUX`, following [here](https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html#variables-that-describe-the-system).

From my experiment it didn't work for my ubuntu 20.04 environment.

https://github.com/intel/hexl/blob/3b7e2d54e4fcdc5ffb6448b9323076f6844e6b65/CMakeLists.txt#L124

**Comment by hamishun** [comment]
@wkjung Thank you for bringing this to our attention. The cmake code will be changed in a future release. Fortunately, this issue does not affect the build of HEXL.
