### ISSUE TITLE
EltwiseReduceMod fails on EltwiseReduceModAVX512 operation with a modulus that is between 51 and 52 bits.

### ISSUE THREAD

**Issue by jcalafato1** [intel/hexl#121]
The library does not reduce properly for any modulus between 51 and 52 bits. See this test:

TEST(ReduceFailure, ReduceFailure) {
  std::vector<uint64_t> tst = {
    41834706795195925,
    4670328046076965,
    17760383643480343,
    49435670237278413,
    24379914680392825,
    33362919182756282,
    14501318335168678,
    31183658415687847
  };
  auto mod = 4440955546175441;
  auto chk  = tst;
  intel::hexl::EltwiseReduceMod(chk.data(), tst.data(), tst.size(),
                                mod,
                                mod, 1);
  auto exp = tst;
  for (auto & elem : exp) {
    elem %= mod;
  }
  ASSERT_EQ(exp, chk);
}

This is just an example. I have tried several different moduli of the same bit width and several different inputs. The reduction function does not match the modulus operation.

**Comment by joserochh** [comment]
Hello @jcalafato1 I have reproduced this issue with a modulus size of 52 bits but not 51 bits. Do you have a 51 bits case that you can share? I think this is a limitation of the IFMA algorithm on big inputs.

**Comment by jcalafato1** [comment]
Hey @joserochh thanks for getting back to me, is a fix available or is it just a limitation of the library? I have a workaround in my projects to prevent 52 bit moduli from being generated right now, but I'd rather not have the restriction.

I also misspoke, it is a 52 bit number that doesn't work, so no worries with 51 bits.

**Comment by joserochh** [comment]
There will be a fix so you don't need to avoid 52 bit moduli. In the worst case, the library will have to use AVX512-DQ intrinsic functions instead of AVX512-IFMA for this scenario. When input values are not that big, say only up to 4 times modulus value (input_mod_factor), then reduction works fine with 52 bit moduli on IFMA as the algorithm is way simpler.

**Comment by jcalafato1** [comment]
Sounds good, thanks! I'll watch for a new version.

**Comment by joserochh** [comment]
Fix is on dev branch.
