### ISSUE TITLE
Add a port file to vcpkg?

### ISSUE THREAD

**Issue by WeiDaiWD** [intel/hexl#5]
FYI, you can create a port file in vcpkg so that we can add a feature to SEAL:
```powershell
./vcpkg install seal       # installs SEAL without HEXL
./vcpkg install seal[hexl] # installs SEAL with HEXL
```

**Comment by fboemer** [comment]
Thanks for the tip! This would be a nice feature; we'll take a look.

**Comment by WeiDaiWD** [comment]
Let me know if I can help.

**Comment by WeiDaiWD** [comment]
I took the liberty of adding "hexl" to vcpkg, See [pull request](https://github.com/microsoft/vcpkg/pull/18043).
We want to add "building APSI with HEXL enabled" to Microsoft/APSI's readme. Since we recommend building dependencies of APSI via vcpkg, we need HEXL to be there. :)

There are requirements in vcpkg that makes this PR really difficult. I'm working on it. Basically, HEXL's downloading `cpu-features` is not allowed in vcpkg, since the better way is to install `cpu-features` from vcpkg and to call `find_package(CpuFeatures ...)` in HEXL. But `cpu-features` installed by vcpkg has an issue too, which make `find_package(CpuFeatures ...)` fail all the time. I might have to add patches to both packages.

Anyway, nothing requires any change in HEXL so far. This is likely to be approved next week.

**Comment by fboemer** [comment]
> I took the liberty of adding "hexl" to vcpkg, See [pull request](https://github.com/microsoft/vcpkg/pull/18043).
> We want to add "building APSI with HEXL enabled" to Microsoft/APSI's readme. Since we recommend building dependencies of APSI via vcpkg, we need HEXL to be there. :)
> 
> There are requirements in vcpkg that makes this PR really difficult. I'm working on it. Basically, HEXL's downloading `cpu-features` is not allowed in vcpkg, since the better way is to install `cpu-features` from vcpkg and to call `find_package(CpuFeatures ...)` in HEXL. But `cpu-features` installed by vcpkg has an issue too, which make `find_package(CpuFeatures ...)` fail all the time. I might have to add patches to both packages.
> 
> Anyway, nothing requires any change in HEXL so far. This is likely to be approved next week.

Thanks, @WeiDaiWD! Let us know if you need any support from the hexl side.

**Comment by WeiDaiWD** [comment]
FYI, two minor things that I've noticed:
- `HEXLConfig.cmake`is not ignored.
- `HEXLConfig.cmake`, `HEXLConfigVersion.cmake`, `HEXLTargets.cmake`, and `HEXLTargets-release.cmake` are installed to `/usr/local/lib/cmake` rather than `/usr/local/lib/cmake/HEXL` (or better `/usr/local/lib/cmake/HEXL-1.1`).

These are unrelated to this issue. :)

**Comment by WeiDaiWD** [comment]
Finally we have `hexl` added to `vcpkg`, [this PR](https://github.com/microsoft/vcpkg/pull/18043) is merged. So now you can install `hexl` with `./vcpkg install hexl`. On Windows, you have to use `./vcpkg install hexl:x64-windows-static` or `./vcpkg install hexl:x64-windows-static-md`. The reason why dynamic linking won't work on Windows is that HEXL does not export symbols.

I'm gonna add an option to install SEAL with HEXL enabled to `vcpkg`, e.g., `./vcpkg install seal[hexl]` soon.

**Comment by fboemer** [comment]
Thanks, @WeiDaiWD! We'll see if we can fix the Windows dynamic build.

**Comment by WeiDaiWD** [comment]
No pressure. I was just describing what is supported when installing via vcpkg. SEAL does not support windows dynamic either. :)
