### ISSUE TITLE
hexl failed microsoft seal 

### ISSUE THREAD

**Issue by lidh15** [intel/hexl#88]
the new version 3.7.1 mircosoft seal failed to work with hexl 1.2.2
[seal issue 411](https://github.com/microsoft/SEAL/issues/411)

**Comment by lidh15** [comment]
ok, it's said to be fixed in pull request #90 4 days ago but nobody informed me here which makes me look stupid.

**Comment by fboemer** [comment]
@lidh15, apologies for the oversight.
